name: Terraform CI

on:
  push:
    branches:
      - feature/terraform-infrastructure
      - main

  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Enviroment/preprod

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve tfplan